# Name of the workflow – this shows up in the GitHub Actions UI
name: Python CI

# Define when this workflow should run
on:
  # Run the workflow every time someone pushes code to the 'main' branch
  push:
    branches:
      - main
  # Run the workflow for pull requests targeting the 'main' branch
  pull_request:
    branches:
      - main

# Define the jobs in this workflow
jobs:
  test:  # Job name
    # The type of machine to run on (Ubuntu Linux in this case)
    runs-on: ubuntu-latest

    # List of steps to execute in this job
    steps:
      # Step 1: Check out the repository code so the workflow can access it
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up a specific version of Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version to use

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt      # Install all required packages listed in requirements.txt

      # Step 4: Run tests using pytest
      - name: Run tests
        run: pytest  # This will run all test files that start with 'test_' or end with '_test.py'
